name: Getting Started Grupo Ramos CI

on: [push, pull_request]
jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    env:
      LOCAL_IMAGE_TAG: local/getting-started:latest
      REMOTE_IMAGE_TAG: ${{ secrets.MMC_REPO }}/hmarzan/getting-started:latest
    steps:
    - name: Source Checkout
      uses: actions/checkout@v4

    - name: Docker login
      run: | 
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login \
          --username=${{ secrets.REGISTRY_USERNAME }} \
          --password-stdin ${{ secrets.MMC_REPO }}
      
    - name: Build Image
      run: docker build . --file Dockerfile --tag ${{ env.LOCAL_IMAGE_TAG }}

    - name: Tag Image
      run: docker tag ${{ env.LOCAL_IMAGE_TAG }} ${{ env.REMOTE_IMAGE_TAG }}
          
    - name: Push to Registry
      run: docker push -- ${{ env.REMOTE_IMAGE_TAG }}

    - name: Docker logout
      run: docker logout

